### ISSUE TITLE
Changing pie chart radius.

### ISSUE THREAD

**Issue by BrysovVadik** [kevinzhow/PNChart#196]
It would be great if there would be a possibility to change the radius of pie chart.

**Comment by brigoodwinan** [comment]
The only way I know how to do this is to actually modify the block of code in PNPieChart.m:


@implementation PNPieChart

-(id)initWithFrame:(CGRect)frame items:(NSArray *)items{
    self = [self initWithFrame:frame];
    if(self){
        _items = [NSArray arrayWithArray:items];
        _outerCircleRadius  = CGRectGetWidth(self.bounds) / 2;
        _innerCircleRadius  = 0;//CGRectGetWidth(self.bounds) / 4; // Set the inner circle radius here!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        
        _descriptionTextColor = [UIColor whiteColor];
        _descriptionTextFont  = [UIFont fontWithName:@"Avenir-Medium" size:18.0];
        _descriptionTextShadowColor  = [[UIColor blackColor] colorWithAlphaComponent:0.4];
        _descriptionTextShadowOffset =  CGSizeMake(0, 1);
        _duration = 1.0;
        
        [super setupDefaultValues];
        [self loadDefault];
    }
    
    return self;
}


This is a total hack, but it would be nice if there was an easy way to change it. Otherwise, really neat stuff.

**Comment by BrysovVadik** [comment]
Thanks for the reply, I already did something similar.
